from flask import Flask, render_template
import json
import os
import time
import threading

# Importamos las funciones core de tu Agente y tu Enriquecedor
from agent import collect_running_processes, save_telemetry_to_disk
from enricher import check_double_extensions, check_reverse_shell, check_suspicious_processes, check_process_masquerading, check_reconnaissance_tools, check_temp_execution, save_alerts_to_disk

app = Flask(__name__)

# Paths to the data files generated by the agent and enricher engines
ALERTS_FILE = "data/alerts.json"
TELEMETRY_FILE = "data/telemetry.json"

def read_json_file(file_path):
    """Reads a JSON file and returns its content."""
    if not os.path.exists(file_path):
        return []
    try: 
        with open(file_path, 'r', encoding='utf-8') as file:
            return json.load(file)
    except json.JSONDecodeError:
        print(f"Error decoding JSON from {file_path}. Returning empty list.")
        return []
    
def background_enrichment_loop():
    """
    Background thread that continuously enriches telemetry data and generates alerts.
    This loop runs independently of the Flask web server, ensuring real-time updates.
    """
    while True:
        try:
            #1 the agent recolects the latest telemetry snapshot
            snapshot = collect_running_processes()
            save_telemetry_to_disk(snapshot, TELEMETRY_FILE)

            #2 the enricher applies heuristic rules to detect suspicious processes
            alerts = []
            alerts.extend(check_suspicious_processes(snapshot))
            alerts.extend(check_process_masquerading(snapshot)) 
            alerts.extend(check_reconnaissance_tools(snapshot))    
            alerts.extend(check_double_extensions(snapshot))  
            alerts.extend(check_temp_execution(snapshot))
            alerts.extend(check_reverse_shell(snapshot))
            #save alerts to disk
            with open(ALERTS_FILE, 'w', encoding='utf-8') as f:
                json.dump(alerts, f, indent=4)
            print(f"[*] Background enrichment loop completed. {len(alerts)} alerts generated.")
        except Exception as e:
            print(f"[!] Error in background enrichment loop: {e}")

        #wait for next iteration (e.g., 15 seconds)
        time.sleep(15)

@app.route('/')
def dashboard():
    """
    Main web application route. Loads fresh security logs from disk,
    computes real-time statistics, and feeds data into the HTML template.
    """
    # 1. Ingests the latest snapshots from teh telemetry logs
    alerts= read_json_file(ALERTS_FILE)
    telemetry = read_json_file(TELEMETRY_FILE)

    #2 pre-calculate metrics for the top dashboard overview cards
    stats = {
        "total_alerts": len(alerts),
        "total_processes": len(telemetry),
        "critical_alerts": sum(1 for a in alerts if a.get("severity") == "CRITICAL"),
        "high_alerts": sum(1 for a in alerts if a.get("severity") == "HIGH")
    }
    # render the frontend view using the Jinja2 template engine, passing in the telemetry and alert data
    return render_template('dashboard.html', telemetry=telemetry, alerts=alerts, stats=stats)

if __name__ == "__main__":
    bg_thread = threading.Thread(target=background_enrichment_loop, daemon=True)
    bg_thread.start()
    print("[*] Starting miniEDR Web Dashboard on http://127.0.0.1:5000")
    
    # 2. Desactivamos el reloader automático para evitar que se ejecute el hilo por duplicado
    app.run(debug=True, use_reloader=False)