from flask import Flask, render_template, request
import json
import os
import time
import threading

# Importamos las funciones core de tu Agente y tu Enriquecedor
from agent import collect_running_processes, save_telemetry_to_disk
from enricher import check_double_extensions, check_reverse_shell, check_suspicious_processes, check_process_masquerading, check_reconnaissance_tools, check_temp_execution, save_alerts_to_disk
from vt_connector import check_file_hash_vt, VT_API_KEY,VT_BASE_URL
from file_analyzer import scan_directory_executables, save_files_to_disk
app = Flask(__name__)

# Paths to the data files generated by the agent and enricher engines
ALERTS_FILE = "data/alerts.json"
TELEMETRY_FILE = "data/telemetry.json"
FILES_TELEMETRY_FILE = "data/files_telemetry.json"

def read_json_file(file_path):
    """Reads a JSON file and returns its content."""
    if not os.path.exists(file_path):
        return []
    try: 
        with open(file_path, 'r', encoding='utf-8') as file:
            return json.load(file)
    except json.JSONDecodeError:
        print(f"Error decoding JSON from {file_path}. Returning empty list.")
        return []

def process_vt_batch(telemetry_file_path):
    """
    Identifies and triages a batch of up to 4 pending files against VirusTotal.
    Keeps the main enrichment thread decoupled and clean.
    """
    if not os.path.exists(telemetry_file_path):
        return

    try:
        with open(telemetry_file_path, "r", encoding="utf-8") as f:
            files_data = json.load(f)

        # Select up to 4 non-scanned files from the inventory
        targets = [f for f in files_data if not f.get("vt_scanned", False)][:4]

        if not targets:
            return

        print(f"[*] VT Batch: Processing batch of {len(targets)} pending files...")
        
        for target_file in targets:
            found, positives = check_file_hash_vt(target_file['sha256'])
            
            target_file["vt_scanned"] = True
            target_file["vt_positives"] = positives

            # Commit updates to disk after each lookup to avoid data loss
            with open(telemetry_file_path, "w", encoding="utf-8") as f:
                json.dump(files_data, f, indent=4)
                
            # Technical micro-sleep to prevent socket throttling during bursts
            time.sleep(1)

        print("[+] VT Batch: Evaluation completed for the current iteration.")

    except Exception as e:
        print(f"[!] Exception encountered inside VirusTotal batch module: {e}")


def background_enrichment_loop():
    """
    Background thread that continuously enriches telemetry data and generates alerts.
    This loop runs independently of the Flask web server, ensuring real-time updates.
    """
    while True:
        try:
            #1 the agent recolects the latest telemetry snapshot
            snapshot = collect_running_processes()
            save_telemetry_to_disk(snapshot, TELEMETRY_FILE)

            #2 the enricher applies heuristic rules to detect suspicious processes
            alerts = []
            alerts.extend(check_suspicious_processes(snapshot))
            alerts.extend(check_process_masquerading(snapshot)) 
            alerts.extend(check_reconnaissance_tools(snapshot))    
            alerts.extend(check_double_extensions(snapshot))  
            alerts.extend(check_temp_execution(snapshot))
            alerts.extend(check_reverse_shell(snapshot))
            #save alerts to disk
            save_alerts_to_disk(alerts, ALERTS_FILE)

            # 3. check the file telemetry for unscanned files and query VirusTotal
            process_vt_batch(FILES_TELEMETRY_FILE)

        except Exception as e:
            print(f"[!] Error in background enrichment loop: {e}")
        #wait for next iteration (e.g., 15 seconds)
        time.sleep(60)

@app.route('/')
def dashboard():
    """
    Main web application route. Loads fresh security logs from disk,
    computes real-time statistics, and feeds data into the HTML template.
    """
    # 1. Ingests the latest snapshots from teh telemetry logs
    alerts= read_json_file(ALERTS_FILE)
    telemetry = read_json_file(TELEMETRY_FILE)

    #2 pre-calculate metrics for the top dashboard overview cards
    stats = {
        "total_alerts": len(alerts),
        "total_processes": len(telemetry),
        "critical_alerts": sum(1 for a in alerts if a.get("severity") == "CRITICAL"),
        "high_alerts": sum(1 for a in alerts if a.get("severity") == "HIGH")
    }
    # render the frontend view using the Jinja2 template engine, passing in the telemetry and alert data
    return render_template('dashboard.html', telemetry=telemetry, alerts=alerts, stats=stats)

@app.route('/alert/details')
def alert_details():
    """
    Renders detailed forensic telemetry for a specific incident in a new tab.
    Expects query parameters: rule, pid, name, path, user, timestamp, status, remote_address
    """
    # Extract query arguments sent from the dashboard frontend link
    details = {
        "rule": request.args.get('rule', 'N/A'),
        "pid": request.args.get('pid', 'N/A'),
        "name": request.args.get('name', 'N/A'),
        "path": request.args.get('path', 'N/A'),
        "user": request.args.get('user', 'N/A'),
        "timestamp": request.args.get('timestamp', 'N/A'),
        "status": request.args.get('status', 'RUNNING'),
        "remote_address": request.args.get('remote_address')
    }
    
    # Render the new dedicated forensic details template view
    return render_template('alert_details.html', details=details)

if __name__ == "__main__":
    bg_thread = threading.Thread(target=background_enrichment_loop, daemon=True)
    bg_thread.start()
    print("[*] Starting miniEDR Web Dashboard on http://127.0.0.1:5000")
    
    # 2. Desactivamos el reloader automático para evitar que se ejecute el hilo por duplicado
    app.run(debug=True, use_reloader=False)